# A12-Q40
# Find the Longest Repeat in a String

Text = "CCATGGCACCGTAACCTATCCCAACTGGCCGACTTATATTTCTAAATTCGGAGCTTGACTAGTGGCATCACCCATCTGAAGATCAGTTGCTTTTGAGACCGCTTCTTCGCGGTCTGGCGGGCTCGGCAAGTAAGTCACAACATGGACACACCCCAAGGACATAAGTCTCACGAACATTACCGAGCATGCAACACGAATACCAAGGCTTCTGCCGAGCTCTGGTGCAATAACCCATACTATTCAGACTTTTGAGATCAGGCCCAAAATGAATAGCCAGGGTTACGAGGTCTAGAGCAGAGCCAGGAGACGACAAGGTAGTTTACAAACTCCTTTGCCAGTACGTTGCGCCAAGTGTCGCGCCCGATGTCGAATGAATTGTCGGGATACGACAGCAGACTCCACGATCAAACTCCCCGAGCTGCTGATTTAGCTGCTGATTTATTCTTACAACACTTAACCCAACCGGCGCACGGAAGGTTGAGTGACATGCTACCGGACATGGTGCAATCGCTTTATTCTTACAACACTTAACCCAACCGGCGCACGGAAGGTTGAGTGACATGCTACCGGACATGGTGCAATCGCTTTTTTCTAAAGGGATTGACAGATTATGCTCACCCTAGAGGGGCGTGCAGAATTCCCCCTAGGTTCTAACCGCAGAGAACAATGACAGCACCAGTTTTTGGTCATGGTCCAGCCAACGGGGTAAGGACTTTCCGTGGCTCGGTGGCGCGCTTCAAAGGGCACGGAAATCATTCCGTACCGCTTGTGTTGTGTATAGTGGGCCCCGATCCGACGGATTAGTGTCTATAGTAGCCCTCGTCAAAAGATAGTAAATTGCCACACAAGTGGTTACTGGTGGAGAAAGACGTCCAAACTGTGTAACCAACTCGTGCATAGAACCAGTGACACAGCTGCTGATTTATTCTTACAACACTTAACCCAACCGGCGCACGGAAGGTTGAGTGACATGCTACCGGACATGGTGCAATCGCTTTATGTTCCCGAATGTCCCGGGACATCAAAACCTAGTCTCATCCATGCCCGGATGTGTGTAACGAAAGACAACTACGAATCAAGTCAACTATTCGCCCGACGCCGGCTCGGTGCGTGTGATTTAGTTTCATTACGTTTGGCTACGGACACCGCCACAGCTCGCGAAAATTGATATGACGTGTCCTCCCTCGGGATATGCTCTATGCCTCATTGGATTTATCACGTATAGACAGTGTTCGACTGCGTGTGGGAACACTATTAT"


def build_suffix_array(s):
    return sorted(range(len(s)), key=lambda i: s[i:])


def build_lcp(s, sa):
    n = len(s)
    rank = [0] * n
    for i, pos in enumerate(sa):
        rank[pos] = i

    lcp = [0] * (n - 1)
    h = 0
    for i in range(n):
        r = rank[i]
        if r == 0:
            continue
        j = sa[r - 1]
        while i + h < n and j + h < n and s[i + h] == s[j + h]:
            h += 1
        lcp[r - 1] = h
        if h > 0:
            h -= 1
    return lcp


def longest_repeat(text):
    """
    Returns one longest substring that appears at least twice in text.
    If no repeat exists, returns empty string.
    """
    n = len(text)
    if n <= 1:
        return ""

    sa = build_suffix_array(text)
    lcp = build_lcp(text, sa)

    if not lcp:
        return ""

    max_lcp = max(lcp)
    if max_lcp == 0:
        return ""

    # First position where this max LCP occurs: between sa[idx-1] and sa[idx]
    idx = lcp.index(max_lcp) + 1
    start = sa[idx]
    return text[start:start + max_lcp]


def main():
    result = longest_repeat(Text)
    print(result)


if __name__ == "__main__":
    main()
