# A12-Q43
# Pattern Matching with the Suffix Array

Text = "TCACCGAGATCGGGCCGGTGTGAGTGTCGATGCTCAAGATAGACGACTGAGCGCCTAATAGTCAATGCAGACGATAACAAAGCCAAGCCCGAGAAGCGCACTTGCTGACCCTCTGAGGCAGGGCCCTCGGTAATGTGAATATACTTAGGCGCTTCTTGCTGGGCATAGGTACACAACGGCAAATGGCAACCTCCAGTTAGGCCAACCTTACGCCCCTCATGCATTTCTTTCATGCAAACCCACAGTTTAGATGGGACACTGGAGAACTCCGAATCCTCTCGTTGCAGTATAGACTAGGGCGCGGCCCCTACGGTCCGAGTTTCCAGGCCGAGTCCGTGTACAGGCGCCAGCGGACCATGAAGTTATGGTCTGTCGCGTTCGACCTTAAGAACCTTAGGTTGTCAACTGCAGATGAAAGTTCCCGGACACTCATTAATGTAAACTGCGGTAGCAGTCAAACGCGAACTGCAACGCTGATTGAACATTGAACATTTGGGCGGGCTGCGCTATACATAAGACGTTCATTGAACATTGAACATCCTCGCCTCAAGCATCATACACTTGGTGACGTGGTCTTCTGACCTCGGCCTCACGCCTCACGCTGGCTGGGCGTAGTAACCCCACCGTGTCCTAACAATCGGAGTTATATACGGAGGCTGACGTGATGGCCACGGTATCTGGAACCCGTTGGCCTCCTGGGAGCGTCAAGCATGACGAGAGTCGCGTACAATTTACAATATCATTTTTCACCTGTTAGCGTAGCTCAAAGACATTGAACATTGAACATGCTCTATGAGCAGAGACACTAGAGGAGTCCGCAGGCCTGTCCGCTATACTCTTGAATTACGATATTGCCTGGATATCCTGGGCCAGCTTTTGGCTCTGTAAATTATCGTGCGGCCTCACGCCGGGGTTGGTACAGGTTGTCGAATTTTTTCTCAGGTCCTGCTTCCTGCTGCATAGTCAATAGTCAATCGCCCAAGTGTATAGGGGCTCTCGAAAGTTTTGGAATCGACGTGTTGTGTCACTCCAACAAAGCCCGAGGGAACTTTGCCGCTTAGTCATTCCAAGCCCACCAGAAACAATGGAGCTGATCACTTTCTACGCTTTAGGCACGTCCTACAATCCGACTCGTGATCCAAATTATACCAGACATAAACTTTCTGGGACTAGCGTCAGAGCATTTGCCAAATACGCTTGTAGGCCCCCTGCCACAGAGAGGGATGAAGGCTATGATTAAGAGAAGTTCAGTATCTCCTTGTGGTCTCCGGTGTATCTCTCAGGTCTCAGGTCATACGACCCCTCGGTGAGCGTGTTAGCACAACTAGACGAGATGTACAAGTACCGGGCTACTCCCAAAATTCACCACGTATCATCCCGAGGTGGTACCAATGTACTAGAGACTAGAGACTACTACGTATGGACGATGAGATGATACCGATTTCTGAAGCTTCCTGCTATGGAATAGTCAATAGTCAATTGGTAGTTGCTGCTTCCTGCTTCCTGCAGAGAATATACATAACCGCGAAATTATAGTGACTTTACGGAGTCAGTATCGGTTACATTGAACATCTTCCTGCGGCGCGGCATTACCGGCCCGCCAGTCGTCTTAGAATAACGGCACAGATCGGCTTTAGTGGTTGGGCCGTCAACGTTTTAAATCGTGTATCCTCAACTATCACACGGATAGAGACTACTACACCTCACCTGGATAGAGAAATAGAGACTAGAGACTATCCTTCGCATAGTGTGGATGAAGGATGAAGGGTCAATTATGACCAATTGACATGTCGCTTTGACGAATATTCTTCGATGAACAAGCAAGTCGGACTGCTATCTGGCCCTTCCTCCGCCTACGCGCTGCAGATCCGTTTATCAGAGGAGCCCCTAACCCAGTTCTCTCAGGTCACGTATCGGGCTATCCGGGGATGGATCAATCATCCAACAGGCCCGCATGTCGACGACCAAGATGCGGATAAACTCGTTCGGGGAGGACGAAGGGATGAAGGATGAAGGCCCGCATGCGTCAGGACTTATTGCGTCAGTCATGCGCGGTGCAAATAGAAACGGGCGGATGAAGGATGTCGTATTATTCATGGTGCGCTTGTCCGACAATCAATCATCTAAGCAAGAAATTCCAGCGCTTCCTGCGACTGCGGACTCGGTATTTCCGTCCCCGACTACTTTTGTTTAAATGAGTCTTCACGAAGCCGATGTCAAGATTTAGAGACTAGAGACTATACTTGAATACAGGAGGATAGCGACAGCCTCACGCCTCACGCTAGTATCACACGGATTCTAATAGCCTCACGCCTCACGCAGATCCGATTGAACATTGAACATTTTTGTACTGACTGTCATCGCTACAGTCGATATCTCAGGTCAGTGATTACGACACCTCATGACATGATAAGTTAAGATAGAGACTAAGGTACTTGGACAATCTATCGCTCTGCACCTACCACGAGAGCCCAAAAAACTAATAACT"
Patterns = [
    "GCTTCCTGC",
    "ATAGTCAAT",
    "GGATGAAGG",
    "GCCTCACGC",
    "TCTCAGGTC",
    "ATTGAACAT",
    "TAGAGACTA"
]


def build_suffix_array(text):
    if not text.endswith("$"):
        text += "$"
    suffixes = [(text[i:], i) for i in range(len(text))]
    suffixes.sort(key=lambda x: x[0])
    return [i for _, i in suffixes]


def suffix_array_search(text, sa, pattern):
    """
    Binary search on suffix array to find pattern occurrences.
    """
    n = len(text)

    # ---- left bound search ----
    l, r = 0, n
    while l < r:
        m = (l + r) // 2
        if text[sa[m]:].startswith(pattern) or text[sa[m]:] > pattern:
            r = m
        else:
            l = m + 1
    left = l

    # ---- right bound search ----
    l, r = 0, n
    # Next lexicographic string after pattern
    pat_hi = pattern[:-1] + chr(ord(pattern[-1]) + 1)
    while l < r:
        m = (l + r) // 2
        if text[sa[m]:] >= pat_hi:
            r = m
        else:
            l = m + 1
    right = l

    # Extract valid matches
    return [sa[i] for i in range(left, right) if text[sa[i]:].startswith(pattern)]


def main():
    sa = build_suffix_array(Text)

    all_matches = []
    for p in Patterns:
        all_matches.extend(suffix_array_search(Text, sa, p))

    all_matches = sorted(set(all_matches))
    print(" ".join(map(str, all_matches)))


if __name__ == "__main__":
    main()
